BUs = [ 'BLR', 'GUR', 'KOA', 'HEC' ]
employees = [
    {'Vorname': 'Marcel', 'Name': 'Albl', 'BU': 'BLR'},
    {'Vorname': 'Simon', 'Name': 'Alther', 'BU': 'GUR'},
    {'Vorname': 'Beat ', 'Name': 'Besmer', 'BU': 'BLR'},
    {'Vorname': 'Roger', 'Name': 'Billeter', 'BU': 'KOA'},
    {'Vorname': 'Rachel', 'Name': 'Blaser', 'BU': 'BAR'},
    {'Vorname': 'Ruth', 'Name': 'Bopp', 'BU': 'JUS'},
    {'Vorname': 'Sandro', 'Name': 'Brandt', 'BU': 'GUR'},
    {'Vorname': 'Lukas', 'Name': 'Brun', 'BU': 'GUR'},
    {'Vorname': 'Manuel', 'Name': 'Brändli', 'BU': 'BLR'},
    {'Vorname': 'Reto', 'Name': 'Bättig', 'BU': 'BAR'},
    {'Vorname': 'Josua', 'Name': 'Cantieni', 'BU': 'BLR'},
    {'Vorname': 'Samuel', 'Name': 'Dobmann', 'BU': 'GUR'},
    {'Vorname': 'Zhuo Yan', 'Name': 'Du', 'BU': 'HEC'},
    {'Vorname': 'Nicolas', 'Name': 'Ehrenberg', 'BU': 'BLR'},
    {'Vorname': 'Markus', 'Name': 'Frei', 'BU': 'GUR'},
    {'Vorname': 'Andreas', 'Name': 'Fröwis', 'BU': 'GUR'},
    {'Vorname': 'Linard', 'Name': 'Furck', 'BU': 'BLR'},
    {'Vorname': 'Heinz', 'Name': 'Füglister', 'BU': 'BAR'},
    {'Vorname': 'Stefan', 'Name': 'Geringer', 'BU': 'BLR'},
    {'Vorname': 'Michael', 'Name': 'Giessel', 'BU': 'KOA'},
    {'Vorname': 'Riccardo', 'Name': 'Gubser', 'BU': 'BAR'},
    {'Vorname': 'Gianni', 'Name': 'Gugolz', 'BU': 'BLR'},
    {'Vorname': 'Sibille', 'Name': 'Hablützel', 'BU': 'BLR'},
    {'Vorname': 'Christoph', 'Name': 'Hafner (M&F)', 'BU': 'BAR'},
    {'Vorname': 'Christian', 'Name': 'Hecht', 'BU': 'BAR'},
    {'Vorname': 'Florian', 'Name': 'Herzog', 'BU': 'KOA'},
    {'Vorname': 'Thomas', 'Name': 'Hindermann', 'BU': 'BLR'},
    {'Vorname': 'Peter', 'Name': 'Huber', 'BU': 'KOA'},
    {'Vorname': 'Benjamin', 'Name': 'Imbach', 'BU': 'GUR'},
    {'Vorname': 'Frank', 'Name': 'Jordi', 'BU': 'KOA'},
    {'Vorname': 'Bruno', 'Name': 'Knoepfel', 'BU': 'KOA'},
    {'Vorname': 'Adrian', 'Name': 'Kohlbrenner', 'BU': 'BAR'},
    {'Vorname': 'Maximilian', 'Name': 'Lienen', 'BU': 'GUR'},
    {'Vorname': 'Stefan', 'Name': 'Lochau', 'BU': 'GUR'},
    {'Vorname': 'Markus', 'Name': 'Meier', 'BU': 'KOA'},
    {'Vorname': 'Binasa', 'Name': 'Misinovic', 'BU': 'JUS'},
    {'Vorname': 'David', 'Name': 'Ochsner', 'BU': 'BLR'},
    {'Vorname': 'Linus', 'Name': 'Riedi', 'BU': 'GUR'},
    {'Vorname': 'Simon', 'Name': 'Rodoni', 'BU': 'BLR'},
    {'Vorname': 'Marco', 'Name': 'Schiltknecht', 'BU': 'BLR'},
    {'Vorname': 'Remo', 'Name': 'Schär', 'BU': 'HEC'},
    {'Vorname': 'Leonie', 'Name': 'Sommer', 'BU': 'BLR'},
    {'Vorname': 'Simeï', 'Name': 'Steiner', 'BU': 'BLR'},
    {'Vorname': 'Ruedi', 'Name': 'Steinmann', 'BU': 'GUR'},
    {'Vorname': 'Severin', 'Name': 'Thöni', 'BU': 'KOA'},
    {'Vorname': 'Stefan', 'Name': 'Wenk', 'BU': 'HEC'},
    {'Vorname': 'Florian', 'Name': 'Wernli', 'BU': 'BLR'},
    {'Vorname': 'Maximilian', 'Name': 'Wolfertz', 'BU': 'BLR'},
    {'Vorname': 'Raphael', 'Name': 'Wüest', 'BU': 'HEC'},
    {'Vorname': 'Miroslaw', 'Name': 'Yan', 'BU': 'BLR'}
]
